name: Build and Test API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - maain

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal
